# https://github.com/serverless/examples/tree/master/aws-ruby-simple-http-endpoint

service: service-notifications

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-dotenv-plugin
custom:
  dotenv:
    path: ./.env
    include:
      - DYNAMODB_ACCESS_KEY_ID
      - DYNAMODB_SECRET_ACCESS_KEY

provider:
  name: aws
  runtime: ruby2.5
  environment:
    DYNAMODB_ACCESS_KEY_ID: ${env:DYNAMODB_ACCESS_KEY_ID}
    DYNAMODB_SECRET_ACCESS_KEY: ${env:DYNAMODB_SECRET_ACCESS_KEY}
    ENVIRONMENT: production

functions:
  make_request:
    memorySize: 128
    timeout: 20s
    handler: handler.make_request
    events:
      - http:
          path: make_request
          method: post
